version: '3'
services:
  nginx:
    image: nginx: stable version
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./php:/var/www/html
  php:
    image: php:()
    volumes:
      - ./php:/var/www/html
